wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699938011.027435
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 83
      3:
      - 17
      - 19
      - 23
      - 37
      4: 3.8.18
      5: 0.16.0
      6: 4.35.0
      8:
      - 3
      - 5
      13: windows-amd64
training:
  desc: null
  value: true
inference:
  desc: null
  value: false
model_dir:
  desc: null
  value: /output/models\2023-11-14 14:00:07.182492.pt
dataset_dir:
  desc: null
  value: dataset
wandb:
  desc: null
  value: true
pretrained_model_name_or_path:
  desc: null
  value: runwayml/stable-diffusion-v1-5
rank:
  desc: null
  value: 4
latent_dim:
  desc: null
  value: 4096
num_features:
  desc: null
  value: 6
num_classes:
  desc: null
  value: 18
revision:
  desc: null
  value: null
optim_type:
  desc: null
  value: AdamW
resolution:
  desc: null
  value: 256
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 16
alpha_1:
  desc: null
  value: 0.0001
alpha_2:
  desc: null
  value: 0.1
