wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699931387.634294
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 83
      3:
      - 17
      - 23
      4: 3.8.18
      5: 0.16.0
      6: 4.35.0
      8:
      - 3
      - 5
      13: windows-amd64
